// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
// Create Project
export const SET_ORDER = 'SET_ORDER'
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'

export const CREATE_CHARGE = 'CREATE_CHARGE'
export const CREATE_CHARGE_SUCCESS = 'CREATE_CHARGE_SUCCESS'
